# Generated by Django 3.2.5 on 2021-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('city', models.TextField()),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
